### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by aaronsr** [jamiemo/k8s-eks-aws-auth-configmap#1]
I don't have an issue, I just wanted to send a big thanks for creating this. I have been struggling with this particular issue for a few days and your solution worked perfectly.

**Comment by jamiemo** [comment]
I'm glad it worked out for you. It took some time to sort this out. Worth doing if it helps someone else out.

**Comment by jamiemo** [comment]
@aaronsr you may want to add prevent_destroy = true as per the latest commit, to avoid accidentally removing the other entries.
